Esercizi svolti
csunibo/ing-sistemi-operativi-t pull request #3
Opened 2023-04-19 15:36 UTC by AleOrcia

Creazione file contenente link a repository con esercizi svolit

2023-04-19 16:24 UTC, foxyseta requested changes
Ciao! Se usi l'estensione `.link` anziché `. txt` il tuo collegamento viene automaticamente interpretato come tale, anziché aprire un file di testo semplice che contiene solo quel collegamento.

2023-04-19 16:39 UTC, AleOrcia reviewed
rinominato estensione da .txt a .link come suggerito da @foxyseta

2023-04-19 18:22 UTC, foxyseta approved these changes

2023-04-19 18:23 UTC, merged

2023-04-21 12:23 UTC, VaiTon commented
@foxyseta next time squash pls che altrimenti si fanno troppi commit inutili